### ISSUE TITLE
Error: listen EADDRINUSE :::35729

### ISSUE THREAD

**Issue by ulivz** [ulivz/blog#1]
# Summary

Run：`npm run dev`,  error occurred as follows: 

```
> v2js@1.0.0 dev /Users/haolchen/Documents/__self__/blog
> gulp dev

[15:20:12] Using gulpfile ~/Documents/__self__/blog/gulpfile.js
[15:20:12] Starting 'dev'...
[15:20:12] Starting 'watch'...
[15:20:12] Starting 'docsify'...

Serving /Users/haolchen/Documents/__self__/blog/docs now.
Listening at http://localhost:3000

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::35729
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at Server.listen (/Users/haolchen/Documents/__self__/blog/node_modules/livereload/lib/livereload.js:66:28)
    at Object.exports.createServer (/Users/haolchen/Documents/__self__/blog/node_modules/livereload/lib/livereload.js:224:14)
    at Object.module.exports [as serve] (/Users/haolchen/Documents/__self__/blog/node_modules/docsify-cli/lib/commands/serve.js:29:12)
    at Gulp.gulp.task.done (/Users/haolchen/Documents/__self__/blog/gulpfile.js:31:20)
    at module.exports (/Users/haolchen/Documents/__self__/blog/node_modules/orchestrator/lib/runTask.js:34:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v2js@1.0.0 dev: `gulp dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v2js@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haolchen/.npm/_logs/2017-08-26T07_20_12_180Z-debug.log
```

**Comment by ulivz** [comment]
# Analysis
 
```
Error: listen EADDRINUSE :::35729
```
means that `35729` has been used, so the solution is to find who use it, and kill it.

> lsof -i:35729
> kill -9 <result>
